# Generated by Django 5.1.4 on 2025-01-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_holder_name',
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
