# Generated by Django 5.1.4 on 2025-01-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productitem_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'ProductItem', 'verbose_name_plural': 'ProductItems'},
        ),
        migrations.AlterModelTable(
            name='productitem',
            table=None,
        ),
    ]
