# Generated by Django 5.1.4 on 2025-01-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productitem_options_alter_productitem_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_image_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
            ],
            options={
                'verbose_name': 'ProductVariation',
            },
        ),
        migrations.CreateModel(
            name='ProductVariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariation')),
            ],
            options={
                'verbose_name': 'ProductVariationOption',
            },
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productitem')),
                ('variation_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariationoption')),
            ],
            options={
                'verbose_name': 'ProductConfig',
            },
        ),
    ]
